exports.SERVICE_NAME = "rpc_test";
exports.GRAPE_URL = "http://127.0.0.1:30001";

exports.ORDER_TYPE = {
  ADD_NEW_ORDER: "ADD_NEW_ORDER",
  LIST_ALL_ORDERS: "LIST_ALL_ORDERS",
};

exports.ORDER_STATUS = {
  NEW: "NEW",
  PENDING: "PENDING",
  PARTIALLY_COMPLETED: "PARTIALLY_COMPLETED",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR",
};
